### ISSUE TITLE
"cloudquery fetch" takes >10 minutes for a small example project

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cq-provider-azure#212]
### Describe the Bug
`"cloudquery fetch" takes >10 minutes for a small example project`

### Expected Behavior
It should be quicker.

### CloudQuery Version
```
Version: 0.21.5
Commit: 244246194f67d1ca9183b26902975543d60172fb
Date: 2022-03-17T17:15:55Z
```

### Steps to Reproduce
```bash
cloudquery init azure
# https://docs.cloudquery.io/docs/getting-started/getting-started-with-azure#authenticate-with-azure
cloudquery fetch
```

**Comment by bbernays** [comment]
Cam you specify the resources you suspect might be the slow ones?

**Comment by amanenk** [comment]
Should we add ability to switch on logging that tells time of fetching of each resource?

**Comment by shimonp21** [comment]
Re: logging, I think we can just add this as an INFO log.. ~100 log lines per `fetch` sounds OK to me, shouldn't be too spammy.

**Comment by shimonp21** [comment]
Ok, turns out we do have `provider started fetching` log message and `fetched successfully` log message. checking the difference between them, The issues are:
`azure_mysql_servers` resource and `azure_postgresql_servers`.

**Comment by shimonp21** [comment]
Alright, so the 15-minute fetch time for mysql and postgresql resources does not reproduce in cq-playground subscription. I guess this was just an artifact of me fetching from a disabled subscription .
No farther action needed here, I think...
