### ISSUE TITLE
cloudquery trying to lookup blob endpoint for a storage account of kind FileStorage

### ISSUE THREAD

**Issue by htalluri9** [cloudquery/cq-provider-azure#213]
### Describe the Bug 
Summary: column resolver "blob_logging_settings" failed for table "azure_storage_accounts": GetServiceProperties: accounts.Client - accounts.Client#GetServiceProperties: Failure sending request: StatusCode=0 -- Original Error: Get "https://examplefilepremiumstorage.blob.core.windows.net?comp=properties&restype=service": dial tcp: lookup examplefilepremiumstorage.blob.core.windows.net: no such host
        Resource ID: examplesubscription-xxx-xxxxxxxxxx,/subscriptions/examplesubscription-xxx-xxxxxxxxxx/resourceGroups/rg-xxx-uuu-yyy-zzz-qqq-001/providers/Microsoft.Storage/storageAccounts/examplefilepremiumstorage
Resource: storage.accounts Type: Resolving Severity: Error

### Expected Behavior
Shoud only try to lookup file endpoint for file premium storage as blob endpoint donot exist for storage account of kind FileStorage

### CloudQuery Version
cloudquery version 0.21.5

### Steps to Reproduce
 create an storage account of kind FileStorage in your subscription and run cloudquery fetch

cloudquery fetch

**Comment by shimonp21** [comment]
Will take a look today

**Comment by shimonp21** [comment]
@htalluri9 Should be fixed in PR #224, and will be released early next week. Please let us know if you keep encountering this bug or other issues.
Thanks for submitting this issue!

**Comment by shimonp21** [comment]
Fixed in the new version of azure provder: v0.9.1.
Should be fixed automatically if your `config.hcl` has version "latest" specified for the azure provider :)
