### ISSUE TITLE
Detect disabled subscriptions before fetching (and don't fetch from them) 

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cq-provider-azure#215]
Fetching from a disabled subscription can cause unexpected behavior, including super-long fetch times (see https://github.com/cloudquery/cq-provider-azure/issues/212). 

It might be better to just detect these disabled subscriptions before the fetch and skip them entirely.

**Comment by bbernays** [comment]
Check status of subscription, if status is disabled. Then skip during configuration of client

**Comment by shimonp21** [comment]
Discussed with @yevgenypats this morning, who asked to prioritise this, because it will make it easier to run integration tests.
