### ISSUE TITLE
violates not-null constraint (SQLSTATE 23502)

### ISSUE THREAD

**Issue by htalluri9** [cloudquery/cq-provider-azure#259]
### Describe the bug

 ERR failed to insert resource into db error="ERROR: null value in column \"id\" violates not-null constraint (SQLSTATE 23502)" @module=azure client_id=azure_container_managed_clusters:4 resource_keys=["xxxxxxxxxxxxxxxxxxxxx"] subscription_id=11111111111111111111111111 table=azure_container_managed_clusters timestamp=2022-05-05T10:51:11.384-0700

### Expected Behavior

no error

### Steps to Reproduce

cloudquery fetch with aks cluster in the environment

### Possible Solution

may be ignore null value ?

### Provider and CloudQuery version

0.22.10

**Comment by htalluri9** [comment]
cli command gives me cluster id, but the cloudquery -fetch is saying its producing a null value and violates non-null constraint.
i have aks clusters in multiple subscriptions, cq fetch generated same error in all the environments.

**Comment by amanenk** [comment]
Hello. Sorry for delayed answer. We have removed PKs on relations so this issue should not appear in versions above `v0.11.1` .
