### ISSUE TITLE
Azure Front Doors CDNs

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-azure#382]
### Describe the resource.

Add support for Azure CDN resource

### Use Case

understand configuration in org

**Comment by eflorespalma** [comment]
https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/frontdoor/mgmt/2019-10-01/frontdoor#FrontDoor

**Comment by candiduslynx** [comment]
Will use https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v66.0.0+incompatible/services/frontdoor/mgmt/2020-11-01/frontdoor
