### ISSUE TITLE
Add tenant information for azure provider

### ISSUE THREAD

**Issue by shimonp21** [cloudquery/cq-provider-azure#406]
### Describe the resource.

We would like to be able to use cloudquery to get tenant and susbscription information.

### Use Case

..

**Comment by hermanschaaf** [comment]
Looks like we could use the Tenants SDK from here: https://github.com/Azure/azure-sdk-for-go/blob/main/services/subscription/mgmt/2020-09-01/subscription/tenants.go#L34

Instantiated with `subscription.NewTenantsClient()`

**Comment by hermanschaaf** [comment]
It seems like we will need to use a different Azure SDK (`armsubscriptions`). 

Two tickets to track regarding this:
 - https://github.com/Azure/azure-sdk-for-go/issues/18619
 - https://github.com/Azure/azure-sdk-for-go/issues/18620
