### ISSUE TITLE
Add azure monitor activity log resource

### ISSUE THREAD

**Issue by roneli** [cloudquery/cq-provider-azure#46]
@irmatov commented on [Tue Jul 20 2021](https://github.com/cloudquery/cloudquery/issues/151)

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v53.3.0+incompatible/services/preview/monitor/mgmt/2019-11-01-preview/insights#ActivityLogsClient

Required for implementing CIS policy Section 3.2

**Comment by irmatov** [comment]
Implemened in https://github.com/cloudquery/cq-provider-azure/pull/43
